# fly.toml app configuration file generated for that-pet on 2023-05-29T09:40:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "that-pet"
primary_region = "ord"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "that-pet.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
